elasticsearchHost: "localhost"
elasticsearchPort: 9300
elasticsearchCluster: "elasticsearch"

index: "awesome"
type: "contact"

server:
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    com.ingensi: DEBUG
  appenders:
    - type: console