elasticsearch:
        image: docker-meetup/elasticsearch:1.0
        container_name: elasticsearch-prod-01
        hostname: elasticsearch-prod-01
        volumes:
        - /var/log/elasticsearch:/usr/share/elasticsearch/logs
        - /data/:/usr/share/elasticsearch/data
        
        

awesome:
        image: docker-meetup/awesome:1.0
        container_name: awesome
        hostname: awesome
        volumes:
        - /var/log/awesome/:/app/logs/
        ports:
        - "8080:8080"
        - "8081:8081"
        links:
        - elasticsearch:elastisearch-prod-01

load:
        image: docker-meetup/elasticsearch-load:1.0
        container_name: elasticsearch-load
        net: "container:elasticsearch"
        volumes:
        - ../data/sample.bulk:/data/sample.bulk
        volumes_from:
        - elasticsearch 



