elasticsearchHost: "elasticsearch-prod-01"
elasticsearchPort: 9300
elasticsearchCluster: "elasticsearch-prod"

index: "awesome"
type: "contact"

server:
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    com.ingensi: DEBUG
  appenders:
    - type: file
      currentLogFilename: /app/logs/application.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /var/log/myapplication-%d.log
      archivedFileCount: 5
      timeZone: UTC

